FROM --platform=linux/arm64 python:3.11

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update -y && apt-get install -y build-essential libssl-dev libffi-dev python3-dev mariadb-client
RUN apt-get install -yq nano vim
RUN python3 -m pip install pip && pip install --upgrade pip

ENV TZ=Asia/Ho_Chi_Minh

ENTRYPOINT [ "/bin/sh" ]
WORKDIR /backend/

CMD ["/entrypoint.sh"]
